Improve UX when AWS credentials are not found or are for another account
heroku-python/bob-builder pull request #28
Opened 2017-05-12 13:08 UTC by edmorley

**1) Move S3 connection handling to its own class**
This means that the main bucket also benefits from the access denied `anon=True` fall-back previously only used for the upstream bucket. This helps with the case where AWS credentials are found, but are for an account unrelated to either bucket.

Since the main bucket can now fall back to anonymous mode, a check has been added to the deploy command to improve the UX.

Fixes https://github.com/kennethreitz/bob-builder/issues/26#issuecomment-301058112.

**2) Support no AWS credentials being found in the environment**
This allows the build command to be used with public buckets even if the user doesn't have their own AWS credentials.

Fixes #26.

**3) Defer S3 connections until Formula instantiation**
This prevents unnecessary connections to S3 or resultant error messages when running `bob --help`.

Fixes #27.

2017-05-12 19:26 UTC, kennethreitz commented
This looks good. Left a few comments on the code before merging.

2017-05-12 19:27 UTC, kennethreitz requested changes
Left a few comments on the code before merging.

2017-05-12 19:27 UTC, kennethreitz commented on bob/models.py
> +            print 'ERROR: Deploy requires valid AWS credentials!'
let's print this to `std_err`

2017-05-12 19:27 UTC, kennethreitz commented on bob/utils.py
> +            print 'No AWS credentials found. Requests will be made without authentication.'
this to `stderr` too.

2017-05-12 19:27 UTC, kennethreitz commented on bob/utils.py
> +class S3ConnectionHandler(object):
Docstrings!

2017-05-16 23:23 UTC, edmorley commented on bob/models.py
> +            print 'ERROR: Deploy requires valid AWS credentials!'
The other (existing) error messages go to stdout. Would you like me to switch those over to stderr in this PR too?

2017-05-16 23:53 UTC, kennethreitz commented on bob/models.py
> +            print 'ERROR: Deploy requires valid AWS credentials!'
that'd be great!

2017-05-24 18:21 UTC, edmorley commented
I've updated the PR. Changes made:
* The new `S3ConnectionHandler` class now has a docstring.
* Errors now output to stderr (using `print_function` as suggested [here](https://stackoverflow.com/questions/5574702/how-to-print-to-stderr-in-python)) and the error messages cleaned up slightly.
* `S3_BUCKET` not being set is now handled gracefully rather than raising a `TypeError` in boto.

2017-05-25 13:06 UTC, edmorley commented
I've also added a commit that fixes #10, seeing as this is already modifying log output.

2017-05-25 14:28 UTC, kennethreitz commented
Visually, this looks solid. We don't have any tests in place, so I'm going to go ahead and merge this and trust that you checked everything was in a good spot. Based on your past PR history, @edmorley, I think this should be good to go :)

2017-05-25 14:28 UTC, merged

2017-05-25 18:19 UTC, edmorley commented
Many thanks! I tested locally and also with heroku/heroku-buildpack-python#387, so fingers crossed :-)

2017-05-26 13:44 UTC, kennethreitz commented
@edmorley what's your pypi user name?

2017-05-26 15:43 UTC, edmorley commented
Demonstrating my lack of creativity, it's `edmorley` there too  :laughing:

2017-05-26 15:47 UTC, kennethreitz commented
@edmorley you are now a maintainer there! You can cut a release :)

P.S. my lack of creativity is the same :)

2017-05-26 15:48 UTC, kennethreitz commented
make sure to tag it in git too

2017-05-30 22:52 UTC, edmorley commented
Tagged and released :-)
https://github.com/kennethreitz/bob-builder/releases/tag/v0.0.13
https://pypi.python.org/pypi/bob-builder/0.0.13